/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashTable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void HashTableTest() {
        HashTable hashtest= new HashTable();
        hashtest.add("adham", 300);
        assertEquals(7, hashtest.hash("adham"));
        assertEquals(300, hashtest.get("adham"));
        assertEquals(false , hashtest.contains("omar"));
        assertEquals(true , hashtest.contains("adham"));


    }
    @Test void repeatedWordTest() {
        HashTable testrepeatWord= new HashTable();

        assertEquals( "was", HashTable.repeatedWord("Once was upon a time,was there was a brave princess who"));
    }
}
