/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code05;

import java.util.LinkedList;

public class App {

    public static void main(String[] args) {
        Linkedlist list = new Linkedlist();
        list.append(1);
        list.append(2);
        list.append(3);
        list.append(4);

        Linkedlist list3 = new Linkedlist();
        list3.append(5);
        list3.append(6);
        System.out.println(list3);
        System.out.println(list);

        Linkedlist list4 = new Linkedlist();
        list4.head = list3.zipLists(list, list3);
        System.out.println(list4.toString());

    }
}
