/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code05;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Linkedlist list = new Linkedlist();
        list.insert(2);
        list.insert(2);
        list.insert(4);
        list.insert(7);

//        list.insertAfter(2,8);
//        list.insertBefore(2,9);
//        list.append(5);
        System.out.println(list.keq(0));



//        System.out.println(list.includes(2));
        System.out.println(list.toString());

    }
}
