/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void addTest(){

        Graph graph = new Graph();

        graph.addNode("1");
        assertEquals("[1]", graph.getNodes().toString());


    }
    @Test
    public void empty(){

        Graph graph = new Graph();
        assertEquals(0,graph.size());

    }
}
