/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code05;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void includes() {
        Linkedlist list = new Linkedlist();
        assertEquals(3,3);
    }
    @Test void s () {
        Linkedlist list = new Linkedlist();
        assertEquals(4,4);
    }

}
