/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;


<<<<<<< HEAD
import com.sun.source.tree.BinaryTree;

import trees.implemant.node.KTree;
import trees.implemant.node.Node;
import trees.implemant.node.NodeK;
import trees.implemant.node.Queue;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

=======
import trees.implemant.BinaryTree;
import trees.implemant.node.Node;
>>>>>>> 8511a8a9411e5635f117b75ca67217fe179d8f70

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());

<<<<<<< HEAD
=======
        Node<Integer> node4 = new Node(1);
        Node<Integer> node5 = new Node(2);
        Node<Integer> node6 = new Node(11);
        Node<Integer> node7 = new Node(3, node6, node6);
        Node<Integer> node2 = new Node(9, node4, node5);
        Node<Integer> node3 = new Node(3, node6, null);

        Node<Integer> root = new Node(4, node2, node3);
        BinaryTree binaryTree = new BinaryTree();

        System.out.println(binaryTree.breadthFirst(root));
>>>>>>> 8511a8a9411e5635f117b75ca67217fe179d8f70

//        Node<Integer> node4 = new Node(1);
//        Node<Integer> node5 = new Node(2);
//        Node<Integer> node6 = new Node(11);
//        Node<Integer> node7 = new Node(3, node6, node6);
//        Node<Integer> node2 = new Node(9, node4, node5);
//        Node<Integer> node3 = new Node(3, node6, null);
//
//        Node<Integer> root = new Node(4, node2, node3);
//
//

//        System.out.println(binaryTree.getSumOdd(root));
//        binaryTree.findMaxValue();
//        binaryTree.insert(1);
//        binaryTree.insert(2);
//        binaryTree.insert(30);
//        binaryTree.insert(4);
//        System.out.println(binaryTree.breadthFirst(binaryTree));


        KTree ktree = new KTree();
        NodeK root = new NodeK("1");
        NodeK node1 = new NodeK("40");
        NodeK node2 = new NodeK("88");
        NodeK node3 = new NodeK("33");
        NodeK node4 = new NodeK("7");
        NodeK node6 = new NodeK("6");

        ktree.root = root;
        root.children.add(node1);
        root.children.add(node2);
        node1.children.add(node3);
        node2.children.add(node4);
        node2.children.add(node6);
        System.out.println(ktree.fizzBuzz(root));
    }

    }





