/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Stake;



public class App {

    public String getGreeting() {
        return "Hello World!";
    }


    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        stackDemo();
        queueDemo();
    }

    private static void stackDemo() {
        Stack stack = new Stack();

        stack.push("A");
        stack.push("D");
        stack.push("H");
        stack.push("A");
        stack.push("M");

        System.out.println("The top of the stack is => " + stack.peek());

        System.out.println(stack.pop());

        System.out.println("The top of the stack is => " + stack.peek());

        System.out.println(stack.pop());
        System.out.println(stack.pop());
        System.out.println(stack.pop());
        System.out.println(stack.pop());
        System.out.println(stack.pop());
    }

    private static void queueDemo() {
        Queue queue = new Queue();

        queue.enqueue("A");
        queue.enqueue("D");
        queue.enqueue("H");
        queue.enqueue("A");
        queue.enqueue("M");

        System.out.println(queue.dequeue());
        System.out.println(queue.dequeue());
        System.out.println(queue.dequeue());
        System.out.println("The front of the Queue is => " + queue.peek());
        System.out.println(queue.dequeue());
        System.out.println(queue.dequeue());
        System.out.println(queue.dequeue());
    }
}
